openapi: 3.0.0
info:
  title: Tamaguru Auth API
  version: 0.1.0
paths:
  /auth/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResp'
  /auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResp'
components:
  schemas:
    RegisterReq:
      type: object
      properties:
        email: {type: string}
        password: {type: string}
    LoginReq:
      type: object
      properties:
        email: {type: string}
        password: {type: string}
    AuthResp:
      type: object
      properties:
        token: {type: string}
        refresh_token: {type: string}
