/*
Tamaguru Auth API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package handler

import (
	"encoding/json"
)

// checks if the AuthResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthResp{}

// AuthResp struct for AuthResp
type AuthResp struct {
	Token *string `json:"token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// NewAuthResp instantiates a new AuthResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthResp() *AuthResp {
	this := AuthResp{}
	return &this
}

// NewAuthRespWithDefaults instantiates a new AuthResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthRespWithDefaults() *AuthResp {
	this := AuthResp{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AuthResp) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResp) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AuthResp) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AuthResp) SetToken(v string) {
	o.Token = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *AuthResp) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthResp) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *AuthResp) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *AuthResp) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o AuthResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableAuthResp struct {
	value *AuthResp
	isSet bool
}

func (v NullableAuthResp) Get() *AuthResp {
	return v.value
}

func (v *NullableAuthResp) Set(val *AuthResp) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthResp) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthResp(val *AuthResp) *NullableAuthResp {
	return &NullableAuthResp{value: val, isSet: true}
}

func (v NullableAuthResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


