/*
Tamaguru Auth API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package handler

import (
	"encoding/json"
)

// checks if the LoginReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginReq{}

// LoginReq struct for LoginReq
type LoginReq struct {
	Email *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// NewLoginReq instantiates a new LoginReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginReq() *LoginReq {
	this := LoginReq{}
	return &this
}

// NewLoginReqWithDefaults instantiates a new LoginReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginReqWithDefaults() *LoginReq {
	this := LoginReq{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *LoginReq) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginReq) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *LoginReq) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *LoginReq) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *LoginReq) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginReq) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *LoginReq) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *LoginReq) SetPassword(v string) {
	o.Password = &v
}

func (o LoginReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableLoginReq struct {
	value *LoginReq
	isSet bool
}

func (v NullableLoginReq) Get() *LoginReq {
	return v.value
}

func (v *NullableLoginReq) Set(val *LoginReq) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginReq) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginReq(val *LoginReq) *NullableLoginReq {
	return &NullableLoginReq{value: val, isSet: true}
}

func (v NullableLoginReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


