openapi: 3.0.0
info:
  title: Tamaguru Auth API
  version: 0.1.0
servers:
- url: /
paths:
  /auth/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterReq"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResp"
          description: OK
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginReq"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResp"
          description: OK
components:
  schemas:
    RegisterReq:
      example:
        password: password
        email: email
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    LoginReq:
      example:
        password: password
        email: email
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    AuthResp:
      example:
        refresh_token: refresh_token
        token: token
      properties:
        token:
          type: string
        refresh_token:
          type: string
      type: object
