name: deploy-vercel-and-backup

on:
  push:
    branches: [main]

jobs:
  deploy-and-backup:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Забираем код
    - uses: actions/checkout@v4

    # 2️⃣ Деплой в Vercel через официальный Action
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: .
        prod: true

    # 3️⃣ Резервная копия «сессии» в S3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1   # поправь, если бакет в другом регионе

    - name: Upload artefacts to S3
      run: |
        TS=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
        zip -r session.zip . -x '.git/*'
        aws s3 cp session.zip s3://tama-sessions/${TS}.zip
