name: deploy_ui
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Build web UI
        run: cd web && npm ci --legacy-peer-deps && npm run build
      - name: OK
        run: echo "build done"
