name: frontend-deploy
on:
  push:
    branches: [feat/login-matrix]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci --prefix web
      - name: Build
        run: npm run build --prefix web
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web/dist
