name: lighthouse
on:
  deployment_status:
    types: [success]
jobs:
  lh:
    runs-on: ubuntu-latest
    steps:
      - uses: treosh/lighthouse-ci-action@v11
        with:
          urls: \"${{ github.event.deployment_status.environment_url }}/login\"
